# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-02 02:00
from __future__ import unicode_literals

import json
import xml.etree.ElementTree as ET

from django.db import migrations, models

from hawc.apps.lit import constants


def add_identifiers(apps, schema_editor):
    for reference in (
        apps.get_model("lit", "Reference").objects.all().prefetch_related("identifiers")
    ):
        reference_changed = False
        for identifier in reference.identifiers.all():
            if identifier.database == constants.PUBMED:
                reference_changed = True
                reference.pubmed_id = int(identifier.unique_id)
                tree = ET.fromstring(json.loads(identifier.content)["xml"])
                el_doi = tree.find('.//ArticleId[@IdType="doi"]')
                if el_doi:
                    reference.doi = el_doi.text

            elif identifier.database == constants.HERO:
                reference_changed = True
                reference.hero_id = int(identifier.unique_id)
                d = json.loads(json.loads(identifier.content)["json"])
                if d.get("DOI"):
                    reference.doi = str(d["DOI"]).strip()
                if d.get("PMID") and d["PMID"].isdigit():
                    reference.pubmed_id = int(d["PMID"])

            else:
                pass

        if reference_changed:
            reference.save()


class Migration(migrations.Migration):

    dependencies = [
        ("lit", "0011_auto_20190416_2035"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference", name="doi", field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="reference",
            name="hero_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reference",
            name="pubmed_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(add_identifiers, reverse_code=migrations.RunPython.noop),
    ]
